# --- Timeout Configs ---
set(HTTP_TIMEOUT_MS 5000)
set(ADC_CONNECTION_CHECK_TIMEOUT_MS 10)
set(SYSTEM_WATCHDOG_TIMEOUT_MS 10000)
set(MAIN_TASK_CYCLE_INTERVAL_MS 1000)

# -- Temperature --
set(SENSOR_TEMPERATURE_MAX_VOLTAGE 3.3)
set(SENSOR_TEMPERATURE_MAX_VALUE 100.0)
set(SENSOR_TEMPERATURE_MIN_VALUE 0.0)

# -- Conductivity --
set(SENSOR_CONDUCTIVITY_MAX_VOLTAGE 3.3)
set(SENSOR_CONDUCTIVITY_MAX_VALUE 15.0)
set(SENSOR_CONDUCTIVITY_MIN_VALUE 0.0)

# -- Flow --
set(SENSOR_FLOW_MAX_VOLTAGE 3.3)
set(SENSOR_FLOW_MAX_VALUE 100.0)
set(SENSOR_FLOW_MIN_VALUE 0.0)